version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Vite runs on port 5173 by default
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development  # Keep it in development for hot-reloading
    command: ["npm", "run", "dev", "--", "--host"]  # Allow external access

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
